
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build exerxise files and website and run server
    init: gradle run distuebungenMarkdown && ./run-website-build.sh
  - name: Webserver on 4000
    command: ./run-server.sh
  - name: Open preview in extra window  
    command: gp preview --external $(gp url 4000)/git-workshop/
  - name: Open exercises view  
    command: gp preview  $(gp url 4000)/git-workshop/aufgaben/
  - name: Übungen
    command: mkdir -p build/git-uebungen/aufgaben; cd build/git-uebungen/aufgaben && ls

ports:
  - port: 4000
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - richardwillis.vscode-gradle
    - fwcd.kotlin
    - eamodio.gitlens
