
image:
  file: .gitpod.Dockerfile

tasks:
  - init: uebungen/gradlew -p uebungen run && cd uebungen/build/git-uebungen/aufgaben && ll
  - command: ./run-server.sh 
  - command: gp preview http://localhost:4000/git-workshop/

ports:
  - port: 4000
    onOpen: ignore

vscode:
  extensions:
    - mathiasfrohlich.kotlin
    - richardwillis.vscode-gradle
