
image:
  file: .gitpod.Dockerfile && cd uebungen/build/git-uebungen/aufgaben && ll

tasks:
  - init: uebungen/gradlew -p uebungen run
  - command: ./run-server.sh 
  - command: gp preview http://localhost:4000/git-workshop/

ports:
  - port: 4000

vscode:
  extensions:
    - mathiasfrohlich.kotlin