
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Open README.md
    command: gp open README.md

  - name: Build exercise files and progress server
    init: gradle build run distuebungenMarkdown
    command: gradle progress

  - name: Build website & Webserver on 4000
    init: ./run-website-build.sh
    command: ./run-server.sh

  - name: Übungen
    command: mkdir -p build/git-uebungen/aufgaben && cd build/git-uebungen/aufgaben && ls

ports:
  - port: 4000
    onOpen: ignore

  - port: 8040
    onOpen: ignore

  - port: 8080
    onOpen: ignore
    visibility: public


vscode:
  extensions:
    - eamodio.gitlens
    - mathiasfrohlich.Kotlin
    - richardwillis.vscode-gradle
