image:
  file: .gitpod.Dockerfile

tasks:
  - before: echo before
#    init: echo bundle && bundle install # runs during prebuild
    command: echo serve && ./run-server.sh

ports:
  - port: 4000
    onOpen: open-preview
